### ISSUE TITLE
Error setting up dotnet step

### ISSUE THREAD

**Issue by smeatond** [JetBrains/ReSharper-InspectCode#12]
Getting this issue when running:

```
jobs:
  inspect:
    name: JetBrains ReSharper Inspect Code
    runs-on: ubuntu-latest
    steps:
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.9
        with:
          settings: .editorconfig
          solution: provi_system.sln
          output: results.html
          format: Html
          sEverity: SUGGESTION
```

Error:

>Run JetBrains/ReSharper-InspectCode@v0.9
Run actions/setup-dotnet@v4
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --runtime dotnet --channel LTS
dotnet-install: Attempting to download using aka.ms link https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.16/dotnet-runtime-8.0.16-linux-x64.tar.gz
dotnet-install: Remote file https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.16/dotnet-runtime-8.0.16-linux-x64.tar.gz size is 31291115 bytes.
dotnet-install: Extracting archive from https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.16/dotnet-runtime-8.0.16-linux-x64.tar.gz
dotnet-install: Downloaded file size is 31291115 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 8.0.16
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --version 8.0.0
dotnet-install: Attempting to download using primary link https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.0/dotnet-sdk-8.0.0-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.0/dotnet-sdk-8.0.0-linux-x64.tar.gz' is not available.
dotnet-install: Attempting to download using primary link https://ci.dot.net/public/Sdk/8.0.0/dotnet-sdk-8.0.0-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://ci.dot.net/public/Sdk/8.0.0/dotnet-sdk-8.0.0-linux-x64.tar.gz' is not available.
dotnet_install: Error: Could not find `.NET Core SDK` with version = 8.0.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
Error: Failed to install dotnet, exit code: 1. dotnet_install: Error: Could not find `.NET Core SDK` with version = 8.0.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

Also tried to downgrade v v0.7 but it still tries to get v8.0.0.

The only fix (but now I get a warning) is when I do:
```
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.9
        with:
          settings: .editorconfig
          solution: provi_system.sln
          output: results.html
          format: Html
          sEverity: SUGGESTION
          dotnet-version: 8.0.410
```
