### ISSUE TITLE
Marketplace information is misleading

### ISSUE THREAD

**Issue by abruner2** [JetBrains/ReSharper-InspectCode#4]
Hey guys, the Marketplace listing for ReSharper Inspect Code shows that the solution variable is optional but in reality it's not. I know this repo is new but I've stumbled upon it and have already started using it!

```
- name: JetBrains ReSharper Inspect Code
  # You may pin to the exact commit or the version.
  # uses: JetBrains/ReSharper-InspectCode@ef165568cb02e723172ccae2b944d713624d43e2
  uses: JetBrains/ReSharper-InspectCode@v0.3
  with:
...
    # Solution file
    solution: # optional
...
```
