### ISSUE TITLE
Space in project name throws "Specify only one solution file" error

### ISSUE THREAD

**Issue by abruner2** [JetBrains/ReSharper-InspectCode#5]
It would seem like RSRP-485105 would have resolved this issue but it's still occuring for me with the GitHub Action. Having a project solution name with a space fails to run with the command line tool. Removing the space in the solution file name (in my private project) seemed to fix the issue.

https://youtrack.jetbrains.com/issue/RSRP-485105/
https://resharper-support.jetbrains.com/hc/en-us/community/posts/4404279451794-InspectCode-Specify-only-one-solution-file
https://github.com/abruner2/Test-Space-Project/actions/runs/5647250274/job/15296962933#step:5:79

**Comment by GCaw** [comment]
Is there a workaround for this (besides renaming the solution), I'm experiencing the same issue running JetBrains/ReSharper-InspectCode@v0.8
My solution has a whitespace in its name, and results in a failure "Specify only one solution file"

```
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.8
        with:
          tool-version: "2024.3.0"
          no-build: "True"
          build: "False"
          solution: $env:Solution_Name

          format: "Xml"
          output: $env:Output_File
          severity: "WARNING"
```
